- become:      yes
  become_user: root
  block:
    - name: Delete default nginx config
      file:
        path:  /etc/nginx/sites-enabled/default
        state: absent

    - name: Add custom 503 error page
      copy:
        src:  503.html
        dest: /var/www/html/503.html

    - name: Create dirs for nginx
      file:
        path:  "{{ item }}"
        state: directory
        owner: project_liberation
        group: project_liberation
        mode:  0755
      with_items:
        - "{{ image_package_dir }}"
        - "{{ static_files_dir }}"
        - "{{ media_files_dir }}"

    - name: Add nginx configs for project-liberation
      template:
        src:  "{{ item }}.j2"
        dest: "/etc/nginx/sites-available/{{ item }}"
      with_items:
        - project-liberation
        - maintenance

    - name: Add nginx configuration snippets for project-liberation
      template:
        src:  "{{ item }}.j2"
        dest: "/etc/nginx/snippets/{{ item }}"
      with_items:
        - configuration-of-compression-timeouts-and-sizes.conf
        - shared-security-headers.conf
