- become:      yes
  become_user: root
  block:
    - name: Delete default nginx config
      file:
        path:  /etc/nginx/sites-enabled/default
        state: absent

    - name: Create dirs for nginx
      file:
        path:  "{{ item }}"
        state: directory
        owner: project_liberation
        group: project_liberation
        mode:  0755
      loop:
        - "{{ image_package_dir }}"
        - "{{ django_static_files_dir }}"
        - "{{ nginx_static_files_dir }}"
        - "{{ media_files_dir }}"

- become: yes
  become_user: "{{ ansible_user_id }}"
  block:
    - name: Generate checksums of nginx html and css files
      local_action: stat path=roles/configure_nginx/files/{{ item }}.css checksum_algorithm=sha256
      register: static_files
      loop: "{{ html_and_css_files }}"

    - include_role:
        name: configure_project_liberation_environment
      vars:
        update_project_liberation_application: "no"
        upload_image_package:                  "yes"

    - name: Extract image package archive
      unarchive:
        src:        "{{ image_package_dir }}/{{ image_package_name }}"
        dest:       /tmp/
        remote_src: yes
      become:      yes
      become_user: project_liberation

    - name: Generate checksums of nginx image files
      stat:
        path: "/tmp/{{ unpacked_image_package_name }}/project_liberation_deployment/http_status_codes/static/{{ item }}.png"
        checksum_algorithm: sha256
      register: image_static_files
      loop: "{{ image_files }}"

- become:      yes
  become_user: root
  block:
    - name: Add css files to custom error pages
      copy:
        src:  "{{ item }}.css"
        dest: "{{ nginx_static_files_dir }}/{{ item }}.{{ static_files.results[html_and_css_index].stat.checksum[:14] }}.css"
        owner: project_liberation
        group: project_liberation
        mode:  0555
      loop: "{{ html_and_css_files }}"
      loop_control:
        index_var: html_and_css_index

    - name: Copy image files to properly directories structure of static files
      copy:
        src:  "/tmp/{{ unpacked_image_package_name }}/project_liberation_deployment/http_status_codes/static/{{ item }}.png"
        dest: "{{ nginx_static_files_dir }}/{{ item }}.{{ image_static_files.results[image_index].stat.checksum[:14] }}.png"
        owner: project_liberation
        group: project_liberation
        mode:  0555
        remote_src: yes
      loop: "{{ image_files }}"
      loop_control:
        index_var: image_index

    - name: Copy the favicon image file to properly directories structure of static files
      copy:
        src:  "/tmp/{{ unpacked_image_package_name }}/project_liberation_deployment/http_status_codes/static/favicon.ico"
        dest: "{{ nginx_static_files_dir }}/favicon.ico"
        owner: project_liberation
        group: project_liberation
        mode:  0555
        remote_src: yes

    - name: Remove temporary image files
      file:
        path:  "/tmp/{{ unpacked_image_package_name }}"
        state: absent

    - name: Add custom error pages
      template:
        src:  "html/{{ item }}.html.j2"
        dest: "/var/www/html/{{ item }}.html"
        owner: project_liberation
        group: project_liberation
        mode:  0555
      loop: "{{ html_and_css_files }}"
      loop_control:
        index_var: html_and_css_index

    - name: Add nginx configs for project-liberation
      template:
        src:  "{{ item }}.j2"
        dest: "/etc/nginx/sites-available/{{ item }}"
      with_items:
        - project-liberation
        - maintenance

    - name: Add nginx configuration snippets for project-liberation
      template:
        src:  "{{ item }}.j2"
        dest: "/etc/nginx/snippets/{{ item }}"
      with_items:
        - configuration-of-compression-timeouts-and-sizes.conf
        - shared-security-headers.conf
