- hosts:
    - project_liberation
  vars_files:
    - consts.yml
    - versions.yml
    - ../../project-liberation-config/var.yml
    - ../../project-liberation-secret/var.yml
  roles:
    - install_dependencies_and_basic_configuration
    - configure_postgres
    - backup
    - configure_mail_alerts
  tasks:
    - become:      yes
      become_user: root
      block:
        - name: Add systemd service for project-liberation app
          template:
            src:  project-liberation-web.service.j2
            dest: /etc/systemd/system/project-liberation-web.service
            mode: 0644

        - name: Enable project-liberation service
          service:
            daemon_reload: yes
            enabled:       yes
            name:          project-liberation-web


        - include_role:
            name: configure_nginx
