- hosts:
    - project_liberation
  vars_files:
    - consts.yml
    - versions.yml
    - ../../project-liberation-config/var.yml
    - ../../project-liberation-secret/var.yml
  roles:
    - install_dependencies_and_basic_configuration
    - configure_postgres
    - backup
    - configure_mail_alerts
  tasks:
    - become:      yes
      become_user: root
      block:
        - name: Add systemd service for project-liberation app
          template:
            src:  project-liberation-web.service.j2
            dest: /etc/systemd/system/project-liberation-web.service
            mode: 0644

        - name: Enable project-liberation service
          service:
            daemon_reload: yes
            enabled:       yes
            name:          project-liberation-web

        - name: Create directory for certificates
          file:
            path:  "{{ certificates_dir }}"
            state: directory
            owner: project_liberation
            group: project_liberation
            mode:  0755

        - name: Check if {{ certificates_dir }} directory is empty
          find:
            paths: "{{ certificates_dir }}"
          register: found_files

        - name: Clear {{ certificates_dir }} before copy valid certificates
          file:
            path: "{{ item.path }}"
            state: absent
          with_items: "{{ found_files.files }}"
          when: found_files.matched > 0

        - name: Copy ssl certificate files to server
          copy:
            src:  "{{ project_liberation_secret_dir }}/{{ item }}"
            dest: "{{ certificates_dir }}/{{ item }}"
            mode:  0644
            owner: project_liberation
            group: project_liberation
          loop:
            - "certificate-privkey.pem"
            - "ssl_trusted_certificate.pem"
            - "ssl_certificate.pem"
            - "ssl-dhparams.pem"

        - include_role:
            name: configure_nginx
