- become:      yes
  become_user: project_liberation
  block:
    - name: Check if project-liberation repository exist
      stat:
        path: "{{ project_liberation_dir }}"
      register: result

    - fail:
        msg: "The project-liberation repository must exist before you can generate static files.
             Please run the deploy.yml playbook with default extra vars \"update_project_liberation_application=yes\" to set up and update project-liberation repository."
      when: not result.stat.exists

    - name: Generate static files
      django_manage:
          command:    collectstatic
          app_path:   "{{ project_liberation_dir }}"
          virtualenv: "{{ project_liberation_virtualenv_dir }}"

    - name: Check if image package exist
      stat:
        path: "{{ image_package_dir }}/{{ image_package_name }}"
      register: image_package_result

    - fail:
        msg: "The image_package must exist before you can extract it.
             Please run the deploy.yml playbook with extra vars \"upload_image_package=yes\" to upload package."
      when: not image_package_result.stat.exists

    - name: Extract image package archive
      unarchive:
        src:        "{{ image_package_dir }}/{{ image_package_name }}"
        dest:       /tmp/
        remote_src: yes

    - name: Copy files to properly structure of directory for static files
      command: rsync -az "{{ item }}" "{{ django_static_files_dir }}/"
      with_items:
        - "/tmp/{{ unpacked_image_package_name }}/company_website/static/"
        - "/tmp/{{ unpacked_image_package_name }}/blog/static/"

    - name: Remove temporary files
      file:
        path:  "/tmp/{{ unpacked_image_package_name }}"
        state: absent
