- include_tasks: update-project-liberation-application.yml
  when: update_project_liberation_application == 'yes'

- include_tasks: upload-secret-file.yml
  when: upload_secret_file == 'yes'

- include_tasks: migrate-database.yml
  when: migrate_database == 'yes'

- include_tasks: upload-image-package.yml
  when: upload_image_package == 'yes'

- include_tasks: generate-static-files.yml
  when: generate_static_files == 'yes'
