- become:      yes
  become_user: project_liberation
  block:
    - name: Check if project-liberation repository exist
      stat:
        path: "{{ project_liberation_dir }}"
      register: result

    - fail:
        msg: "The project-liberation repository must exist before the secret file can be uploaded.
             Please run the deploy.yml playbook with default extra vars \"update_project_liberation_application=yes\" to set up and update project-liberation repository."
      when: not result.stat.exists

    - name: Create secrets directory
      file:
        path:  "{{ project_liberation_dir }}/project_liberation/settings/secrets/"
        state: directory

- become:      yes
  become_user: root
  block:
    - name: Upload secret file
      copy:
        src:   "{{ project_liberation_secret_dir }}/secrets.py.vault"
        dest:  "{{ project_liberation_dir }}/project_liberation/settings/secrets/secrets.py"
        mode:  0644
        owner: project_liberation
        group: project_liberation
