# Generated by Django 2.2.7 on 2019-11-20 15:24

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191118_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('order', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='blogarticlepage',
            name='is_main_article',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogarticlepage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='category_posts', to='blog.BlogCategory'),
        ),
    ]
