# Generated by Django 2.2.7 on 2019-11-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191120_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticlepage',
            name='keywords',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='blogarticlepage',
            name='meta_description',
            field=models.CharField(default='', max_length=168),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='keywords',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='meta_description',
            field=models.CharField(default='', max_length=168),
        ),
        migrations.AddField(
            model_name='blogcategorypage',
            name='keywords',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='blogcategorypage',
            name='meta_description',
            field=models.CharField(default='', max_length=168),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='keywords',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='meta_description',
            field=models.CharField(default='', max_length=168),
        ),
    ]
