# Generated by Django 2.2.7 on 2019-11-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191126_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='title',
            field=models.CharField(default='', help_text="'Search Engine Friendly' title. This will appear at the top of the browser window.", max_length=255, verbose_name='page title'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='keywords',
            field=models.CharField(default='', help_text='Keywords of category page.', max_length=512),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='meta_description',
            field=models.CharField(default='', help_text='Meta description of category page.', max_length=168),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='name',
            field=models.CharField(help_text='Name of category. This name will be shown as a category on blog main page.', max_length=255),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='order',
            field=models.PositiveSmallIntegerField(help_text='Order of categories shown on blog main page menu.'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(help_text='Category page url address. Under this url category page will be searched.', max_length=80, unique=True),
        ),
    ]
