# Generated by Django 2.2.7 on 2019-12-02 15:20

from django.db import migrations, models


def migrate_fields(apps, schema_editor):
    BlogCategory = apps.get_model('blog', 'blogcategory')
    for blog_category in BlogCategory.objects.all():
        blog_category.seo_title = blog_category.title
        blog_category.title = blog_category.name
        blog_category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191128_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='seo_title',
            field=models.CharField(default='', help_text="'Search Engine Friendly' title. This will appear at the top of the browser window.", max_length=255, verbose_name='page seo title'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='title',
            field=models.CharField(help_text='Category title. This name will be shown as a category on blog main page.', max_length=255),
        ),
        migrations.RunPython(migrate_fields),
        migrations.RemoveField(
            model_name='blogcategory',
            name='name',
        ),
    ]
