# Generated by Django 2.2.8 on 2019-12-03 08:24

from django.db import migrations, models
import modelcluster.fields


def migrate_blog_category_to_blog_category_snippet(apps, schema_editor):
    BlogCategory = apps.get_model('blog', 'blogcategory')
    BlogCategorySnippet = apps.get_model('blog', 'blogcategorysnippet')
    for blog_category in BlogCategory.objects.all():
        blog_category_snippet = BlogCategorySnippet(
            title=blog_category.title,
            seo_title=blog_category.seo_title,
            slug=blog_category.slug,
            order=blog_category.order,
            meta_description=blog_category.meta_description,
            keywords=blog_category.keywords,
        )
        blog_category_snippet.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191202_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategorySnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Category title. This name will be shown as a category on blog main page.', max_length=255)),
                ('seo_title', models.CharField(default='', help_text="'Search Engine Friendly' title. This will appear at the top of the browser window.", max_length=255, verbose_name='page seo title')),
                ('slug', models.SlugField(help_text='Category page url address. Under this url category page will be searched.', max_length=80, unique=True)),
                ('order', models.PositiveSmallIntegerField(help_text='Order of categories shown on blog main page menu.')),
                ('meta_description', models.CharField(default='', help_text='Meta description of category page.', max_length=168)),
                ('keywords', models.CharField(default='', help_text='Keywords of category page.', max_length=512)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.RunPython(migrate_blog_category_to_blog_category_snippet),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
        migrations.AlterField(
            model_name='blogarticlepage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='category_posts', to='blog.BlogCategorySnippet'),
        ),
    ]
