# Generated by Django 2.2.8 on 2019-12-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20191203_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticlepage',
            name='keywords',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='blogarticlepage',
            name='meta_description',
            field=models.CharField(blank=True, max_length=168),
        ),
        migrations.AlterField(
            model_name='blogcategorypage',
            name='keywords',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='blogcategorypage',
            name='meta_description',
            field=models.CharField(blank=True, max_length=168),
        ),
        migrations.AlterField(
            model_name='blogcategorysnippet',
            name='keywords',
            field=models.CharField(blank=True, help_text='Keywords of category page.', max_length=512),
        ),
        migrations.AlterField(
            model_name='blogcategorysnippet',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Meta description of category page.', max_length=168),
        ),
        migrations.AlterField(
            model_name='blogcategorysnippet',
            name='seo_title',
            field=models.CharField(blank=True, help_text="'Search Engine Friendly' title. This will appear at the top of the browser window.", max_length=255, verbose_name='page seo title'),
        ),
        migrations.AlterField(
            model_name='blogcategorysnippet',
            name='title',
            field=models.CharField(help_text='Category title. This name will be shown as a category on blog main page.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='blogindexpage',
            name='keywords',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='blogindexpage',
            name='meta_description',
            field=models.CharField(blank=True, max_length=168),
        ),
    ]
