# Generated by Django 2.2.8 on 2019-12-04 11:37

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20191203_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticlepage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(related_name='category_posts', to='blog.BlogCategorySnippet'),
        ),
        migrations.AlterField(
            model_name='blogarticlepage',
            name='read_time',
            field=models.PositiveIntegerField(),
        ),
    ]
