# Generated by Django 2.2.14 on 2020-09-20 21:54

from django.db import migrations
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtailmarkdown.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200908_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticlepage',
            name='body',
            field=wagtail.core.fields.StreamField([('markdown', wagtailmarkdown.blocks.MarkdownBlock(icon='code')), ('header', wagtail.core.blocks.CharBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link', 'image', 'embed', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'code', 'superscript', 'subscript', 'strikethrough', 'blockquote'])), ('table', wagtail.contrib.table_block.blocks.TableBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())]),
        ),
    ]
