# Generated by Django 2.2.17 on 2021-03-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_replace_blogarticlepage_body_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticlepage',
            name='article_photo_alt_description',
            field=models.CharField(blank=True, default='', max_length=125),
        ),
        migrations.AddField(
            model_name='blogarticlepage',
            name='cover_photo_alt_description',
            field=models.CharField(blank=True, default='Open the article', max_length=125),
        ),
    ]
