- become:      yes
  become_user: root
  block:
    - name: Install required packages for apt_key and apt_repository
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl

    - name: Add NodeSource repository key
      apt_key:
        url:   https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present

    - name: Add NodeSource apt repository
      apt_repository:
        repo:  "{{ item }}"
        state: present
      with_items:
        - "deb     https://deb.nodesource.com/node_10.x {{ ansible_distribution_release }} main"
        - "deb-src https://deb.nodesource.com/node_10.x {{ ansible_distribution_release }} main"

    - name: Update apt package index
      apt:  update_cache=yes

    - name: Install basic packages
      apt:
        name:
        - htop
        - ncdu
        - rsync
        - tree
        - tmux
        - vim

    - name: Install dependencies
      apt:
        name:
          - git
          - libgd-dev
          - libgeoip-dev
          - libpcre++-dev
          - libxslt-dev
          - mailutils
          - nginx={{ nginx_version }}
          - nodejs
          - postfix
          - postgresql
          - python3
          - python3-distutils
          - python3-psycopg2
          - python3-setuptools
          - unzip
          - virtualenv
          - wget
          - zlib1g-dev
          - zstd

    - name: Remove unused dependencies
      apt:  autoremove=yes

    - name:    Clear apt cache
      command: apt-get clean

    - name: Create the user account that will be used for project-liberation app
      user:
        name:  project_liberation
        state: present
