# Generated by Django 2.2.6 on 2019-10-24 13:50

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=50)),
                ('front_image', sorl.thumbnail.fields.ImageField(upload_to='whatever')),
                ('back_image', sorl.thumbnail.fields.ImageField(upload_to='whatever')),
                ('order', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
