# Generated by Django 2.2.6 on 2019-10-25 19:23

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='boss',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employees',
            name='back_image',
            field=sorl.thumbnail.fields.ImageField(blank=True, default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='employees',
            name='front_image',
            field=sorl.thumbnail.fields.ImageField(blank=True, default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='employees',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employees',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, unique=True),
        ),
    ]
