# Generated by Django 2.2.6 on 2019-11-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_website', '0002_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectToEstimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=60)),
                ('country', models.CharField(blank=True, max_length=60)),
                ('idea_description', models.TextField(max_length=10000)),
                ('nda_required', models.BooleanField(blank=True, null=True)),
                ('privacy_policy_accepted', models.BooleanField(default=False)),
                ('build_or_improve', models.CharField(blank=True, choices=[('build', 'Build something new'), ('improve', 'Improve existing project')], max_length=15, null=True)),
                ('monthly_bugdet', models.CharField(blank=True, choices=[('-8', 'up to $8.000'), ('8-25', '$8.000 - $25.000'), ('25-100', '$25.000 - $100.000'), ('100+', '$100.000+')], max_length=15, null=True)),
                ('project_time', models.CharField(blank=True, choices=[('-3', 'up to 3 months'), ('3-6', '3-6 months'), ('6+', '6+ months')], max_length=15, null=True)),
                ('design_product', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('company_info_origin', models.CharField(blank=True, choices=[('Google', 'Google'), ('Clutch', 'Clutch.com'), ('Friend', 'Friend'), ('Social Media', 'Social Media'), ('Tech Event', 'Tech Event'), ('Other', 'Other')], max_length=20, null=True)),
            ],
        ),
    ]
