# Generated by Django 2.2.7 on 2019-11-15 11:55

from django.db import migrations, models


def migrate_projects(apps, schema_editor):
    ProjectToEstimate = apps.get_model('company_website', 'ProjectToEstimate')
    EstimateProject = apps.get_model('company_website', 'EstimateProject')
    for project_to_esttimate in ProjectToEstimate.objects.all():
        estimate_project = EstimateProject(
            creation_date=project_to_esttimate.creation_date,
            name=project_to_esttimate.name,
            email=project_to_esttimate.email,
            country=project_to_esttimate.country,
            idea_description=project_to_esttimate.idea_description,
            nda_required=project_to_esttimate.nda_required,
            privacy_policy_accepted=project_to_esttimate.privacy_policy_accepted,
            project_development=project_to_esttimate.build_or_improve,
            monthly_bugdet=project_to_esttimate.monthly_bugdet,
            project_duration=project_to_esttimate.project_time,
            design_product=project_to_esttimate.design_product,
            company_info_origin=project_to_esttimate.company_info_origin,
        )
        estimate_project.full_clean()
        estimate_project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('company_website', '0003_projecttoestimate'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=60)),
                ('country', models.CharField(blank=True, max_length=60)),
                ('idea_description', models.TextField(max_length=10000)),
                ('nda_required', models.BooleanField(blank=True, null=True)),
                ('privacy_policy_accepted', models.BooleanField(default=False)),
                ('project_development', models.CharField(blank=True, choices=[('build', 'Build something new'), ('improve', 'Improve existing project')], max_length=15, null=True)),
                ('monthly_bugdet', models.CharField(blank=True, choices=[('-8', 'up to $8.000'), ('8-25', '$8.000 - $25.000'), ('25-100', '$25.000 - $100.000'), ('100+', '$100.000+')], max_length=15, null=True)),
                ('project_duration', models.CharField(blank=True, choices=[('-3', 'up to 3 months'), ('3-6', '3-6 months'), ('6+', '6+ months')], max_length=15, null=True)),
                ('design_product', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('company_info_origin', models.CharField(blank=True, choices=[('Google', 'Google'), ('Clutch', 'Clutch.com'), ('Friend', 'Friend'), ('Social Media', 'Social Media'), ('Tech Event', 'Tech Event'), ('Other', 'Other')], max_length=20, null=True)),
            ],
        ),
        migrations.RunPython(migrate_projects, reverse_code=migrations.RunPython.noop),
        migrations.DeleteModel(
            name='ProjectToEstimate',
        ),
    ]
