# Generated by Django 2.2.7 on 2019-11-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_website', '0004_auto_20191115_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(choices=[('MAIN_PAGE', 'Main Page'), ('TEAM_INTRODUCTION', 'Team Introduction'), ('HOW_WE_WORK', 'How we Work'), ('CAREER', 'Career'), ('ESTIMATE_PROJECT', 'Estimate Project'), ('PRIVACY_AND_POLICY', 'Privacy and Policy')], max_length=40, unique=True)),
                ('title', models.CharField(max_length=80)),
                ('meta_description', models.CharField(max_length=168)),
                ('keywords', models.CharField(max_length=512)),
            ],
            options={
                'verbose_name': 'Page SEO',
                'verbose_name_plural': 'Pages SEO',
            },
        ),
    ]
