# Generated by Django 2.2.11 on 2020-06-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_website', '0006_employees_is_working'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageseo',
            name='page_name',
            field=models.CharField(choices=[('MAIN_PAGE', 'Main Page'), ('TEAM_INTRODUCTION', 'Team Introduction'), ('HOW_WE_WORK', 'How we Work'), ('CAREER', 'Career'), ('ESTIMATE_PROJECT', 'Estimate Project'), ('PRIVACY_AND_POLICY', 'Privacy and Policy'), ('THANK_YOU', 'Thank You')], max_length=40, unique=True),
        ),
    ]
