# Generated by Django 2.2.11 on 2020-06-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_website', '0007_auto_20200625_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimateproject',
            name='monthly_bugdet',
            field=models.CharField(blank=True, choices=[('-8', 'up to $8.000'), ('8-25', '$8.000 — $25.000'), ('25-100', '$25.000 — $100.000'), ('100+', '$100.000+')], max_length=15, null=True),
        ),
    ]
