# Generated by Django 2.2.14 on 2020-10-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_website', '0008_auto_20200625_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='display_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employees',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
