# Generated by Django 2.2.14 on 2020-12-02 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_website', '0010_estimateprojectemailrecipients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimateproject',
            name='company_info_origin',
        ),
        migrations.RemoveField(
            model_name='estimateproject',
            name='country',
        ),
        migrations.RemoveField(
            model_name='estimateproject',
            name='design_product',
        ),
        migrations.RemoveField(
            model_name='estimateproject',
            name='monthly_bugdet',
        ),
        migrations.RemoveField(
            model_name='estimateproject',
            name='nda_required',
        ),
        migrations.RemoveField(
            model_name='estimateproject',
            name='project_development',
        ),
        migrations.RemoveField(
            model_name='estimateproject',
            name='project_duration',
        ),
    ]
