# Generated by Django 2.2.17 on 2021-08-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_website', '0012_employees_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageseo',
            name='page_name',
            field=models.CharField(choices=[('MAIN_PAGE', 'Main Page'), ('TEAM_INTRODUCTION', 'Team Introduction'), ('HOW_WE_WORK', 'How we Work'), ('CAREER', 'Career'), ('ESTIMATE_PROJECT', 'Estimate Project'), ('PRIVACY_AND_POLICY', 'Privacy and Policy'), ('THANK_YOU', 'Thank You'), ('GO_TO_BRAND_PROJECT', 'Go to Brand')], max_length=40, unique=True),
        ),
    ]
