- become:      yes
  become_user: root
  block:
    - name: Disable nginx proxy to maintenance page information
      file:
        path:  /etc/nginx/sites-enabled/maintenance
        state: absent

    - name: Enable nginx proxy to project-liberation
      file:
        src:   /etc/nginx/sites-available/project-liberation
        dest:  /etc/nginx/sites-enabled/project-liberation
        state: link

    - name: Start project-liberation service
      service:
        name:  project-liberation-web
        state: started

    - name: Restart nginx service
      service:
        name:  nginx
        state: restarted
